### ISSUE TITLE
Problem with Revolut app 

### ISSUE THREAD

**Issue by M1hao** [yzyhk904/hifi-maximizer-mod#25] opened 2024-09-30 11:30 UTC
Hi mate,
Thnx a lot for suberb module! Is there any way to bypass this issue?
![Screenshot_20240929-115128](https://github.com/user-attachments/assets/df629880-0123-498c-83ca-99b560654803)
It only accures after installing Hifi Maximizer.
Thnx!

**Comment by M1hao** [comment] 2024-09-30 11:49
PS. I switched off (not uninstall) magisk module and somehow effect survived. I do not know if it makes sense but it is working know without any conflicts with other apps. Work along with jitter silencer. I am on Pixel 8 Pro

**Comment by yzyhk904** [comment] 2024-10-01 08:21
I guess that the app detected SELinux mode was "Permissive", changed by this module from "Enforcing". The change is a main feature of this module for best audio quality. 

Unless uninstalling this module, some property values (related to wifi and battery) remain in a settings DB even after disabling it and rebooting in the Magisk manager app.

If you are a casual music lover, I recommend you using my another module [Audio Misc. Settings](https://github.com/Magisk-Modules-Alt-Repo/audio-misc-settings) instead.

**Comment by M1hao** [comment] 2024-10-01 08:40
Hi mate,
thank you very much for your reply and great module as well as for usfull informations!
Unfortunately Audio Misc Settings doesn't work for me... There is just silence when using bluetooth headset. 
Anyway I can hear audio improvement without interfering with other apps - jitter and hifi modules are installed but switched off. No audio modification library installed. I am on Android 14, Pixel 8 Pro.
Have a nice day ☀️!

**Comment by yzyhk904** [comment] 2024-10-01 10:57
Audio Misc. Settings disables "Spatial audio" feature on Pixel's. If you disable the feature on settings, you could use Audio Misc Settings. It's a bug that you can use Hifi Maximizer now, and will be fixed in the following release.

Here is a release candidate
[magisk-hifi-maximizer-mod.zip](https://github.com/user-attachments/files/17203776/magisk-hifi-maximizer-mod.zip). An alway 192kHz audio output USB driver hasn't been attached for Pixel 8 and 9 series.

**Comment by M1hao** [comment] 2024-10-01 11:15
Thank you again!

AMS switched off spatial audio in deed after installing but anyway I couldn't hear any sounds. Do you mean phone settings or your mod settings?

I installed the new version but after switching off I get better results with the last, official version. Bug suits me very well 🙂 Only with your module deactivated I can use Revolut.

Regards 
Mihao

**Comment by M1hao** [comment] 2024-10-01 11:36
PS. Do you perhaps know if it's possible to install LHDC codec on my rooted phone? I did some research but nothing has found.

Regards!

**Comment by M1hao** [comment] 2024-10-01 14:57
Cannot install your newest version - Magisk doesn't see it as a installable zip and archiv is grayed. Tried to repack but without success. Any tip?

**Comment by yzyhk904** [comment] 2024-10-02 08:05
I was wrong in the previous comment. I checked the difference between AMS and the latest released Hifi maximizer in sources again, and realized the difference contained SELinux mode and some kernel tunable values. There wasn't in audio configurations.

Did you read README.md? It explains how to disable changing SELinux mode and others (see Note1). Try editing "service.sh" in the module ZIP to disable the change and update with the modified ZIP, and let me know the results.

**Comment by M1hao** [comment] 2024-10-02 09:21
Hi mate,

thanx for reply. Yes, I read before. I edited service.sh file (still writing about Hifi Max) but after re-zipping (with default compression or without) Magisk doesn't read zip and reject it. What am I doing wrong?

Good day for you!

**Comment by yzyhk904** [comment] 2024-10-02 13:54
Why did you unzip? Edit the file in an archiver and overwrite it! A Magisk module zip file is a little bit different from an usual one.

**Comment by M1hao** [comment] 2024-10-02 14:06
I edited on my phone with Solid Explorer which doesn't allow to save zipped files.

**Comment by yzyhk904** [comment] 2024-10-02 15:51
Use Mixplorer (free)!

**Comment by M1hao** [comment] 2024-10-03 09:03
Hi mate,

thank for usfull tip! 

After flashing zip with Selinux Permissive there is just silence  again. With Enforced,  Revolut doesn't work as well as camera - do not know if something else. 

I have sample rate unlocker with jitter silencer installed. This time with AML (have to be installed btw?)

I will follow your module's development anyway.

Thank you for your help and take care!

**Comment by M1hao** [comment] 2024-10-03 09:04
PS. I am open to any further suggestions, tests.

**Comment by yzyhk904** [comment] 2024-10-03 13:03
You misunderstood the SELinux mode. It's reverse. And Hifi maximizer cannot coexist with "USB Samplerate Unlocker". The latest released module has a bug that doesn't warn for uninstalling "USB Samplerate Unlocker". I think your Magisk module manager app in a wrong state. By any chance, it's all the cause.


P.S. Your bluetooth earphones can only work with SELinux PERMISSIVE mode. This is abnormal.

**Comment by M1hao** [comment] 2024-10-03 14:14
I use only jitter + unlocker. My Selinux status is Enforced as I hasitate to switch to Permissive from security reasons (don't know too much about - have to google) Main problem is Revolut (camera too) which doesn't work with permissive mode and I haven't done research so far about how to fix or bypass it. Anyway, sound is better definitely. Thanks you mate.

PS. Mixplorer is great 👍! however not free.
Cheers!

**Comment by yzyhk904** [comment] 2024-10-04 09:27
"USB Samplerate Unlocker" isn't needed on Pixel 8 PRO which can output at 192kHz max. natively. I'm investigating the unlocker if it conflicts to SELinux on the latest firmware of Pixel 8 which might change the SELinux contexts.

I'm guessing that you could get the best result if you install "Audio Misc. Settings", "Audio Jitter Silencer" and "Resampling for cheapies" modules of mine only (after uninstalling "USB Samplerate Unlocker" and "HIFI Maximizer" completely).

P.S> Mixplorer has a full featured free version. See [Mixplorer Download](https://xdaforums.com/t/app-2-2-mixplorer-v6-x-released-fully-featured-file-manager.1523691/post-23109280).

**Comment by M1hao** [comment] 2024-10-04 10:10
Hello 👋,

thanx again for reply and tips!

Audio Misc Settings doesn't transmit any sounds through my bluetooth earplugs. Speakers does .I did what you advised and installed resampling for cheapies + jitter. Sound is good. 

I've already installed Mixplorer Silver but thank you anyway for XDA link - always good to have additional source.

Hava a nice day ☀️!

**Comment by yzyhk904** [comment] 2024-10-05 05:57
I reconsidered your situations, and guess that your Bluetooth earphones are adhered to a spatial audio feature.

Can you try resetting your Bluetooth earphones and pairing after installing Audio Misc. Settings?

**Comment by M1hao** [comment] 2024-10-10 09:29
Hi mate,

it's been a while. Still the same problem after repairing - no sound coming from earplugs. I use OnePlus Buds Pro 2.

Hava a nice day ☀️

**Comment by yzyhk904** [comment] 2024-10-10 15:55
I forgot to mention system property differences between previous version hifi maximizer and latest version audio misc. settings (and latest hifi maximizer). 

Can you check if "Audio misc. settings v1.3.7 (previous version)" works or not? I'm now wondering about the property differences which are related to "Computed Sound Dose" (an adaptive volume level adjustment feature).

P.S. Did you disable all spatial audio features in "Connected devices settings" for each Bluetooth device?

**Comment by M1hao** [comment] 2024-10-11 08:42
Hi mate,

Thanks for reply and info again. 

After installing audio misc settings there's no spatial audio switch in bluetooth headset settings - I assume it is removed by your module itself. Don't have any other connected devices apart from smartwatch.

Previous version AMS doesn't work so I ended up with lastest, published Hifimaximizer (installed but switched off) and jitter silencer. It works fine for me this way.

Have a good day ☀️

**Comment by yzyhk904** [comment] 2024-10-12 07:25
I'm guessing that this issue must be coming from a bug of Pixel 8 PRO which cannot switch off its spatial sound feature in a certain situation. Pixel 8 PRO continues to raise "immersive sound mixer" even after disabling the spatial sound feature though it must switch to "deep buffer mixer" or "default mixer" in this situation.

Since the situation can be avoided by changing SELinux mode to be permissive from your info, you can use root commands: `setenforce 0` (for permissive) and `setenforce 1` ( for enforcing). Those can change the situation on the fly between "on" and "off" though hifi maximizer can only "off" and once at the boot time.

**Comment by M1hao** [comment] 2024-10-12 11:28
Hi and thanx for useful info 👋 👍 

I sticked anyway to enforced one but installed also resample for cheapies as well as USB sample rate unlocker (Hifimaximizer itself is not able to unlock higher frequencies on my phone) and run USB sample rate changer (without unlocker didn't want to unlock anything higher than 96khz). Kind of crazy experiment - never have installed so many sound mods (4, all yours, don't need V4A or James but... who knows? Perhaps I will install one of them on the top of yours continuing experiments🙂?). All of this made sound even better. Hifimaximizer is still switched off as it works only this way. Absolute volume is switched on.

Have a nice weekend ☀️

**Comment by yzyhk904** [comment] 2024-10-13 13:57
As I said before, Pixel 8 PRO can output 192kHz natively. You don't need the unlocker while USB_SampleRate_Changer warns 96kHz without the unlocker. Strictly speaking, only Pixel6 series, Pixel7a and Pixl8a need the unlocker, and other Tensor devices don't (I don't know why Google restricts such).

**Comment by M1hao** [comment] 2024-10-18 08:07
Hi mate,

thx, didn't forget.

Have w nice weekend ☀️!

**Closed as completed** 2024-10-28 08:01 UTC
Labels: question
